version: '3.7'

services:
  blog:
    container_name: blog
    build:
      context: ./blog
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - GITHUB_CLIENT_SECRET_KEY
      - GITHUB_CLIENT_ID
      - GATSBY_GITHUB_SERVER_URL
      - GATSBY_GITHUB_REPOSITORY
    ports:
      - 80:80
      - 443:443
    networks:
      - blog_net
    depends_on:
      - mail_server

  mail_server:
    container_name: mail_server
    build: ./mail-server
    restart: on-failure
    environment:
      - MAIL_HOST
      - MAIL_PORT
      - MAIL_USER
      - MAIL_PASS
      - MAIL_RECIPIENT
    networks:
      - blog_net

networks:
  blog_net:
