name: App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{ secrets.PROD_HOST }}

      - name: Build images
        env:
          GATSBY_GITHUB_SERVER_URL: $GITHUB_SERVER_URL
          GATSBY_GITHUB_REPOSITORY: $GITHUB_REPOSITORY
        run: |
          docker-compose build --no-cache
          docker-compose push
      - name: Deploy
        run: |
          export DOCKER_HOST=ssh://${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}:${{ secrets.PROD_PORT }}

          docker-compose stop
          docker volume rm $(docker volume ls -q)

          docker-compose pull
          docker-compose up -d

          unset DOCKER_HOST
