name: App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{ secrets.PROD_HOST }}

      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 15

      - name: Build js
        run: |
          cd app
          npm i
          npm run build

      - name: Build images
        run: |
          docker-compose build
          docker-compose push

      - name: Deploy
        env:
          GATSBY_GITHUB_SERVER_URL: $GITHUB_SERVER_URL
          GATSBY_GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          MAIL_RECIPIENT: ${{ secrets.MAIL_RECIPIENT }}
        run: |
          export DOCKER_HOST=ssh://${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}:${{ secrets.PROD_PORT }}

          docker-compose pull
          docker-compose up --build --force-recreate -d

          unset DOCKER_HOST
