name: Blog

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Building the app on remote server
        uses: appleboy/ssh-action@master
        env:
          GATSBY_GITHUB_SERVER_URL: $GITHUB_SERVER_URL
          GATSBY_GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          MAIL_RECIPIENT: ${{ secrets.MAIL_RECIPIENT }}
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 20m
          script_stop: true
          script: |
            cd devarticles.space
            git reset --hard origin/main
            git pull
            docker-compose build
            docker-compose up --build --force-recreate -d
            docker system prune -f
